/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally generated by Next.js on first build. It is
// included here so type-checking has the ambient Next types available before
// an install/build has run in this environment.
