/**
 * Minimal, dependency-free invoice PDF generator (Customer Portal).
 *
 * A PDF is a text-based container: a few "objects" (the document catalogue, the
 * page tree, the page, a font, and a content stream) plus a cross-reference
 * table that records each object's byte offset. We build a single A4 page and
 * draw the invoice as positioned text using the standard Helvetica font (one of
 * the 14 fonts every PDF reader has built in, so nothing needs embedding). This
 * avoids a heavyweight PDF dependency entirely and produces a real file a phone
 * browser can open and save. It is intentionally simple — one clean page — which
 * is exactly what a customer wants from an invoice copy.
 */

export interface InvoicePdfData {
  workshopName: string;
  workshopVatId?: string | null;
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  customerName: string;
  customerVatId?: string | null;
  customerCountry?: string | null;
  currency: string;
  reverseCharge: boolean;
  vatNote?: string | null;
  lines: Array<{ description: string; quantity: string; netMinor: string; vatRatePct: string }>;
  totalNetMinor: string;
  totalVatMinor: string;
  totalGrossMinor: string;
}

function money(minor: string | number, currency: string): string {
  const n = Number(minor) / 100;
  return `${currency} ${n.toFixed(2)}`;
}

// Escape the characters that are special inside a PDF text string.
function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

/**
 * Build the page content stream: a list of text draw commands. We work in PDF
 * points (72 per inch); A4 is 595 x 842 pt. Origin is bottom-left, so we lay out
 * from the top (y starts high and decreases).
 */
function buildContent(d: InvoicePdfData): string {
  const left = 56;
  let y = 790;
  const out: string[] = [];

  const text = (x: number, yy: number, size: number, font: 'F1' | 'F2', s: string) => {
    out.push(`BT /${font} ${size} Tf ${x} ${yy} Td (${esc(s)}) Tj ET`);
  };
  const line = (yy: number) => {
    out.push(`${left} ${yy} m 539 ${yy} l S`);
  };

  // Header: workshop name + invoice title.
  text(left, y, 20, 'F2', d.workshopName); y -= 18;
  if (d.workshopVatId) { text(left, y, 9, 'F1', `VAT ID: ${d.workshopVatId}`); }
  text(420, 790, 18, 'F2', 'INVOICE');
  text(420, 770, 10, 'F1', `No. ${d.invoiceNumber}`);
  text(420, 756, 10, 'F1', `Issued: ${d.issueDate}`);
  text(420, 742, 10, 'F1', `Due: ${d.dueDate}`);
  y -= 24;

  // Bill-to.
  text(left, y, 9, 'F1', 'BILL TO'); y -= 14;
  text(left, y, 12, 'F2', d.customerName); y -= 14;
  if (d.customerVatId) { text(left, y, 10, 'F1', `VAT ID: ${d.customerVatId}`); y -= 13; }
  if (d.customerCountry) { text(left, y, 10, 'F1', `Country: ${d.customerCountry}`); y -= 13; }
  y -= 8;
  line(y); y -= 18;

  // Table header.
  text(left, y, 9, 'F2', 'DESCRIPTION');
  text(360, y, 9, 'F2', 'QTY');
  text(430, y, 9, 'F2', 'NET');
  text(500, y, 9, 'F2', 'VAT%');
  y -= 6; line(y); y -= 16;

  // Line items (truncate description so it does not overrun the column).
  for (const l of d.lines) {
    const desc = l.description.length > 52 ? l.description.slice(0, 51) + '…' : l.description;
    text(left, y, 10, 'F1', desc);
    text(360, y, 10, 'F1', l.quantity);
    text(430, y, 10, 'F1', money(l.netMinor, d.currency));
    text(500, y, 10, 'F1', `${l.vatRatePct}%`);
    y -= 16;
    if (y < 140) break; // single-page guard
  }

  y -= 6; line(y); y -= 20;

  // Totals (right-aligned-ish block).
  text(360, y, 10, 'F1', 'Net total:'); text(460, y, 10, 'F1', money(d.totalNetMinor, d.currency)); y -= 15;
  text(360, y, 10, 'F1', 'VAT total:'); text(460, y, 10, 'F1', money(d.totalVatMinor, d.currency)); y -= 15;
  text(360, y, 12, 'F2', 'TOTAL:'); text(460, y, 12, 'F2', money(d.totalGrossMinor, d.currency)); y -= 26;

  // Reverse-charge / VAT note.
  if (d.reverseCharge || d.vatNote) {
    text(left, y, 9, 'F1', d.vatNote ?? 'Reverse charge — VAT to be accounted for by the recipient.');
    y -= 16;
  }
  text(left, 60, 8, 'F1', 'Generated by A-SPRINT Workshop OS — customer portal copy.');

  return out.join('\n');
}

/** Assemble the full PDF byte buffer from the content stream. */
export function generateInvoicePdf(d: InvoicePdfData): Buffer {
  const content = buildContent(d);
  const objects: string[] = [];

  // 1: Catalog, 2: Pages, 3: Page, 4: Font Helvetica, 5: Font Helvetica-Bold, 6: Contents
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
    + '/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const stream = `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`;
  objects.push(stream);

  // Serialise with a cross-reference table (byte offset of each object).
  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdf, 'latin1');
}
