import type { Metadata, Viewport } from 'next';
import { Archivo, IBM_Plex_Sans, IBM_Plex_Mono } from 'next/font/google';
import './../styles/globals.css';
import { DemoBootstrap } from '@/components/demo-bootstrap';

/*
 * Distinctive type pairing (not Inter/Roboto): Archivo as the heavy, condensed
 * display face that reads like stencilled shop signage, IBM Plex Sans as the
 * humanist body, and Plex Mono for clocks, plates, and money figures where a
 * tabular, mechanical feel is right.
 */
const display = Archivo({ subsets: ['latin'], weight: ['600', '700', '800'], variable: '--font-display' });
const body = IBM_Plex_Sans({ subsets: ['latin'], weight: ['400', '500', '600'], variable: '--font-body' });
const mono = IBM_Plex_Mono({ subsets: ['latin'], weight: ['400', '500', '600'], variable: '--font-mono' });

export const metadata: Metadata = {
  title: 'A-SPRINT Workshop OS',
  description: 'AI-native operating system for commercial-vehicle workshops',
  // PWA: link the manifest and the home-screen icon, and declare the iOS
  // standalone behaviour so "Add to Home Screen" launches full-screen with no
  // browser chrome. The manifest itself is generated by app/manifest.ts.
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Workshop OS',
  },
  icons: {
    icon: [{ url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
           { url: '/icon-512.png', sizes: '512x512', type: 'image/png' }],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
};

export const viewport: Viewport = {
  themeColor: '#14181d',
  width: 'device-width',
  initialScale: 1,
  // Cover the iPhone notch area so a home-screen launch is truly full-bleed.
  viewportFit: 'cover',
  // Prevent zoom-jank on tap-heavy mechanic screens while staying accessible.
  maximumScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <body className="min-h-full font-body antialiased">
        <DemoBootstrap>{children}</DemoBootstrap>
      </body>
    </html>
  );
}
