import { Module } from '@nestjs/common';
import { RentalController } from './rental.controller';
import { RentalService } from './rental.service';
import { InvoicesModule } from '../invoices/invoices.module';

/**
 * Vehicle rental module. It composes the existing InvoicesModule (whose
 * InvoicesService.issueFromLines turns the computed rental charges into a real,
 * VAT-correct, Minimax-bound invoice). The global CommonModule supplies PgService,
 * AuditService, and CounterService. The rental contract PDF is generated by a
 * dependency-free helper, mirroring the invoice PDF. There is no separate rental
 * repository because the service's tenant-scoped SQL is small and cohesive.
 */
@Module({
  imports: [InvoicesModule],
  controllers: [RentalController],
  providers: [RentalService],
})
export class RentalModule {}
