/**
 * Minimal, dependency-free rental contract PDF (Phase 12).
 *
 * This mirrors the customer-portal invoice PDF exactly in technique — a hand-
 * assembled PDF using the 14 built-in fonts, no library — so the rental contract
 * is produced the same way every other document in the system is, and renders on
 * any phone. It lays out the legal agreement the customer signs: the parties, the
 * vehicle, the period and locations, the handover/return readings, the full terms
 * (price, deposit, insurance, deductible, fuel/mileage/late policies), and the
 * signature lines required by the contract spec.
 */

export interface RentalContractPdfData {
  workshopName: string;
  workshopVatId?: string | null;
  contractNumber: string;
  // Parties
  customerName: string;
  customerVatId?: string | null;
  customerCountry?: string | null;
  // Vehicle
  vehicle: string;          // "MAN TGX (NM CK-418)"
  vehicleVin?: string | null;
  // Period & locations
  startAt: string;
  endAt: string;
  pickupLocation?: string | null;
  returnLocation?: string | null;
  // Readings (may be blank at draft/handover)
  startMileageKm?: number | null;
  returnMileageKm?: number | null;
  startFuelEighths?: number | null;
  returnFuelEighths?: number | null;
  // Terms
  currency: string;
  dailyRateMinor: number;
  includedKmPerDay: number;
  perKmRateMinor: number;
  depositMinor: number;
  casco: boolean;
  deductibleMinor: number;
  fuelPolicy: string;
  mileagePolicy?: string | null;
  latePolicy?: string | null;
}

function money(minor: number, currency: string): string {
  return `${currency} ${(Number(minor) / 100).toFixed(2)}`;
}
function fuel(eighths?: number | null): string {
  return eighths === null || eighths === undefined ? '—' : `${eighths}/8`;
}
function esc(s: string): string {
  return String(s).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function buildContent(d: RentalContractPdfData): string {
  const left = 56;
  let y = 790;
  const out: string[] = [];
  const text = (x: number, yy: number, size: number, font: 'F1' | 'F2', s: string) => {
    out.push(`BT /${font} ${size} Tf ${x} ${yy} Td (${esc(s)}) Tj ET`);
  };
  const line = (yy: number) => { out.push(`${left} ${yy} m 539 ${yy} l S`); };
  const row = (label: string, value: string) => { text(left, y, 10, 'F1', label); text(250, y, 10, 'F1', value); y -= 15; };

  // Header.
  text(left, y, 20, 'F2', d.workshopName); y -= 18;
  if (d.workshopVatId) text(left, y, 9, 'F1', `VAT ID: ${d.workshopVatId}`);
  text(360, 790, 16, 'F2', 'RENTAL CONTRACT');
  text(360, 770, 10, 'F1', `No. ${d.contractNumber}`);
  y -= 26; line(y); y -= 18;

  // Parties + vehicle.
  text(left, y, 11, 'F2', 'RENTER'); y -= 15;
  row('Customer', d.customerName);
  if (d.customerVatId) row('VAT ID', d.customerVatId);
  if (d.customerCountry) row('Country', d.customerCountry);
  y -= 6;
  text(left, y, 11, 'F2', 'VEHICLE'); y -= 15;
  row('Vehicle', d.vehicle);
  if (d.vehicleVin) row('VIN', d.vehicleVin);
  y -= 6; line(y); y -= 18;

  // Period & locations.
  text(left, y, 11, 'F2', 'PERIOD & LOCATIONS'); y -= 15;
  row('Rental start', d.startAt);
  row('Rental end', d.endAt);
  if (d.pickupLocation) row('Pickup location', d.pickupLocation);
  if (d.returnLocation) row('Return location', d.returnLocation);
  y -= 6; line(y); y -= 18;

  // Readings.
  text(left, y, 11, 'F2', 'MILEAGE & FUEL'); y -= 15;
  row('Starting mileage', d.startMileageKm != null ? `${d.startMileageKm} km` : '—');
  row('Return mileage', d.returnMileageKm != null ? `${d.returnMileageKm} km` : '—');
  row('Starting fuel', fuel(d.startFuelEighths));
  row('Return fuel', fuel(d.returnFuelEighths));
  y -= 6; line(y); y -= 18;

  // Terms.
  text(left, y, 11, 'F2', 'TERMS'); y -= 15;
  row('Daily rate', money(d.dailyRateMinor, d.currency));
  row('Included km/day', String(d.includedKmPerDay));
  row('Extra km rate', money(d.perKmRateMinor, d.currency));
  row('Deposit', money(d.depositMinor, d.currency));
  row('Comprehensive (casco)', d.casco ? 'Yes' : 'No');
  row('Deductible', money(d.deductibleMinor, d.currency));
  row('Fuel policy', d.fuelPolicy);
  if (d.mileagePolicy) row('Mileage policy', d.mileagePolicy);
  if (d.latePolicy) row('Late return policy', d.latePolicy);
  row('Damage responsibility', d.casco ? 'Renter liable up to the deductible' : 'Renter fully liable (no comprehensive cover)');
  y -= 10; line(y); y -= 26;

  // Signature fields.
  text(left, y, 11, 'F2', 'SIGNATURES'); y -= 28;
  out.push(`${left} ${y} m 270 ${y} l S`);
  out.push(`320 ${y} m 539 ${y} l S`);
  y -= 12;
  text(left, y, 9, 'F1', 'Renter (signature, date)');
  text(320, y, 9, 'F1', 'For the workshop (signature, date)');

  text(left, 50, 8, 'F1', 'Generated by A-SPRINT Workshop OS — rental contract.');
  return out.join('\n');
}

/** Assemble the full PDF byte buffer (same object structure as the invoice PDF). */
export function generateRentalContractPdf(d: RentalContractPdfData): Buffer {
  const content = buildContent(d);
  const objects: string[] = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
    + '/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  objects.push(`<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`);

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}
